### PR TITLE
Fix Bug Issue of Meeting created despite group does not exist

### PR DESCRIPTION
**Pull request by Zenious**
Fix bug brought up by issue #173 

Issue:
- Issue is caused by  `setMeeting` method.  
```java
 public void setMeeting(Group group, Meeting meeting) throws GroupNotFoundException {
        meetings.setMeeting(group.getMeeting(), meeting);
        groups.setMeeting(group, meeting);
    }
```  
`meeting` added into `meetings` before being checked if the group exists.

Solution:

- Switched the order of the statement so that `group.setMeeting` will throw exception first before adding `meeting` to `meetings`.
- Added guard statement to check if group exists.

### CODE REVIEW

**Comment by Zenious** [comment]
Written test cases for `MeetingBook#setMeeting` method, but cannot push to repo as test cases failed due to a bug in UniqueMeetingList#setMeeting which raises issues #181, #183, #176.

**Comment by Zenious** [comment]
I believe is it is due to how `meeting` is lookup, it relies on `index` which may be the one causing the problem here.

**Comment by jeffreyooi** [comment]
> I believe is it is due to how `meeting` is lookup, it relies on `index` which may be the one causing the problem here.

I couldn't reproduce the bug. Can I have the reproduction step / the test case that you wrote? Might be able to give a better image on what is happening

**Comment by jeffreyooi** [comment]
Can you try editing `setMeeting` in `MeetingBook` to the following? It is causing error because `group.getMeeting()` has been replaced and therefore when trying to call `UniqueMeetingList#setMeeting` it couldn't find the meeting to edit. To solve this, create a temporary variable to hold the meeting before replacing it in `UniqueGroupList`

`
    public void setMeeting(Group group, Meeting meeting) throws GroupNotFoundException {
        if (hasGroup(group)) {
            Meeting toReplace = group.getMeeting();
            groups.setMeeting(group, meeting);
            meetings.setMeeting(toReplace, meeting);
        } else {
            throw new GroupNotFoundException();
        }
    }
`

**Pull request closed without merging**
